[window]
dimensions = { columns = 102, lines = 28 }
blur = true
padding = { x = 4, y = 4 }
opacity = 0.8
position = { x = 512, y = 400 }

[colors]
primary = { background = "#0d1117" }

[font]
size = 16

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]
